feat(dest/fortinet): fortinet advisory 2023
MaineK00n/network-vuln-feed pull request #5
Opened 2023-05-18 10:02 UTC by 1uf3

2023-05-19 01:48 UTC, MaineK00n commented on dest/fortinet/2023/FG-IR-23-069.json
> -          "cwe": null,
> A relative path traversal vulnerability [CWE-23]

2023-05-19 01:48 UTC, MaineK00n commented on dest/fortinet/2023/FG-IR-23-051.json
> -          "cwe": null,
> a template engine vulnerability [CWE-1336]

2023-05-19 01:49 UTC, MaineK00n commented on dest/fortinet/2023/FG-IR-23-050.json
> -          "cwe": null,
> An improper access control vulnerability [CWE-284]

2023-05-19 01:49 UTC, MaineK00n commented on dest/fortinet/2023/FG-IR-23-013.json
> -          "cwe": null,
> An improper neutralization of input during web page generation ('Cross-site Scripting') vulnerability [CWE-79]

2023-05-19 02:06 UTC, MaineK00n commented on dest/fortinet/2023/FG-IR-23-013.json
> +                    "eq": "9.2"
`9.2 all versions` should be expressed as `9.2.0 through 9.2.x versions`.

2023-05-27 09:31 UTC, 1uf3 commented
not written anything regarding `Workaround for FortiOS`, `Acknowledgement` inside FG-IR-23-001.

2023-06-14 23:42 UTC, MaineK00n requested changes
- resolve conflicts by rebase
- describe the newly added FG-IR-23-*

2023-06-15 09:29 UTC, MaineK00n approved these changes

2023-06-15 09:31 UTC, merged